export {
  IconArrowLeft,
  IconBrandTabler,
  IconSettings,
  IconUserBolt,
  IconX,
  IconUserFilled,
  IconCalendarClock,
  IconReportMedical,
  IconHistory,
  IconPillFilled,
  IconBrandVisa,
  IconReport,
  IconAmbulance,
  IconHelp,
  IconPlus,
  IconClock,
  IconShieldLock,
  IconShieldCheckFilled,
  IconCloudUp,
} from '@tabler/icons-react'
